const myProducts = [
    // Base
   { category: 'base', name: 'Base 1', image: 'base1.png', price: 1400 },
  { category: 'base', name: 'Base 2', image: 'base2.png', price: 1400 },
  { category: 'base', name: 'Base 3', image: 'base3.png', price: 1450 },
  { category: 'base', name: 'Base 4', image: 'base4.png', price: 1450 },
  { category: 'base', name: 'Base 5', image: 'base5.png', price: 1450 },
  { category: 'base', name: 'Base 6', image: 'base6.png', price: 1450 },
  { category: 'base', name: 'Base 7', image: 'base7.png', price: 1450 },
  { category: 'base', name: 'Base 8', image: 'base8.png', price: 1450 },
  { category: 'base', name: 'Base 9', image: 'base9.png', price: 1500 },
  { category: 'base', name: 'Base 10', image: 'base10.png', price: 1500 },
  { category: 'base', name: 'Base 11', image: 'base11.png', price: 1500 },
  { category: 'base', name: 'Base 12', image: 'base12.png', price: 1500 },
  { category: 'base', name: 'Base 13', image: 'base13.png', price: 1500 },
  { category: 'base', name: 'Base 14', image: 'base14.png', price: 1500 },
  { category: 'base', name: 'Base 15', image: 'base15.png', price: 1600 },
  { category: 'base', name: 'Base 16', image: 'base16.png', price: 1600 },
    // mashrabiya
 { category: 'mashrabiya', name: 'mashrabiya 1', image: 'mash1.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya 2', image: 'mash2.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya 3', image: 'mash3.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya 4', image: 'mash4.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya 5', image: 'mash5.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya 6', image: 'mash6.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya 7', image: 'mash7.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya 8', image: 'mash8.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya 9', image: 'mash9.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya 10', image: 'mash10.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya 11', image: 'mash11.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya 12', image: 'mash12.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya with Chandelier 1', image: 'mash51.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya with Chandelier 2', image: 'mash52.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya with Chandelier 3', image: 'mash53.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya with Chandelier 4', image: 'mash54.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya with Chandelier 5', image: 'mash55.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya with Chandelier 6', image: 'mash56.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya with Chandelier 7', image: 'mash57.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya with Chandelier 8', image: 'mash58.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya with Chandelier 9', image: 'mash59.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya with Chandelier 10', image: 'mash60.png', price: 2000 },
  { category: 'mashrabiya', name: 'mashrabiya with Chandelier 11', image: 'mash61.png', price: 2000 },

    // Lighting

  { category: 'profile', name: 'Light 1', image: 'led1.png', price: 300 },
  { category: 'profile', name: 'Light 2', image: 'led2.png', price: 325 },
  { category: 'profile', name: 'Light 3', image: 'led3.png', price: 400 },
  { category: 'profile', name: 'Light 4', image: 'led4.png', price: 400 },
  { category: 'profile', name: 'Light 5', image: 'led5.png', price: 450 },
  { category: 'profile', name: 'Light 6', image: 'led6.png', price: 1000 },
  { category: 'profile', name: 'Light 7', image: 'led7.png', price: 1000 },
  { category: 'profile', name: 'Light 8', image: 'led8.png', price: 1100 },
  { category: 'profile', name: 'Light 9', image: 'led9.png', price: 1100 },
  { category: 'profile', name: 'Light 10', image: 'led10.png', price: 1200 },
  { category: 'profile', name: 'Light 11', image: 'led11.png', price: 1300 },
  { category: 'profile', name: 'Light 12', image: 'led12.png', price: 1400 },
  { category: 'profile', name: 'Light 13', image: 'led13.png', price: 1400 },
  { category: 'profile', name: 'Light 14', image: 'led14.png', price: 1500 },
  { category: 'profile', name: 'Light 15', image: 'led15.png', price: 1500 },
  { category: 'profile', name: 'Light 16', image: 'led16.png', price: 1900 },
];
