const myProducts = [
    // קטגוריית בסיס
   { category: 'base', name: 'דגם 1', image: 'base1.png', price: 6500 },
  { category: 'base', name: 'דגם 2', image: 'base2.png', price: 6500 },
  { category: 'base', name: 'דגם 3', image: 'base3.png', price: 6500 },
  { category: 'base', name: 'דגם 4', image: 'base4.png', price: 6500 },
  { category: 'base', name: 'דגם 5', image: 'base5.png', price: 6500 },
  { category: 'base', name: 'דגם 6', image: 'base6.png', price: 6500 },
  { category: 'base', name: 'דגם 7', image: 'base7.png', price: 6500 },
  { category: 'base', name: 'דגם 8', image: 'base8.png', price: 6500 },
  { category: 'base', name: 'דגם 9', image: 'base9.png', price: 6500 },
  { category: 'base', name: 'דגם 10', image: 'base10.png', price: 6500 },
  { category: 'base', name: 'דגם 11', image: 'base11.png', price: 6500 },
  { category: 'base', name: 'דגם 12', image: 'base12.png', price: 6500 },
  { category: 'base', name: 'דגם 13', image: 'base13.png', price: 6500 },
  { category: 'base', name: 'דגם 14', image: 'base14.png', price: 6500 },
  { category: 'base', name: 'דגם 15', image: 'base15.png', price: 6500 },
  { category: 'base', name: 'דגם 16', image: 'base16.png', price: 6500 },
    // קטגוריית משרביה
 { category: 'mashrabiya', name: 'משרביה דגם 1', image: 'mash1.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה דגם 2', image: 'mash2.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה דגם 3', image: 'mash3.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה דגם 4', image: 'mash4.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה דגם 5', image: 'mash5.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה דגם 6', image: 'mash6.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה דגם 7', image: 'mash7.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה דגם 8', image: 'mash8.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה דגם 9', image: 'mash9.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה דגם 10', image: 'mash10.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה דגם 11', image: 'mash11.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה דגם 12', image: 'mash12.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה נברשת 1', image: 'mash51.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה נברשת 2', image: 'mash52.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה נברשת 3', image: 'mash53.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה נברשת 4', image: 'mash54.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה נברשת 5', image: 'mash55.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה נברשת 6', image: 'mash56.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה נברשת 7', image: 'mash57.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה נברשת 8', image: 'mash58.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה נברשת 9', image: 'mash59.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה נברשת 10', image: 'mash60.png', price: 2000 },
  { category: 'mashrabiya', name: 'משרביה נברשת 11', image: 'mash61.png', price: 2000 },

    // קטגוריית תאורה

  { category: 'profile', name: 'לד דגם 1', image: 'led1.png', price: 600 },
  { category: 'profile', name: 'לד דגם 2', image: 'led2.png', price: 650 },
  { category: 'profile', name: 'לד דגם 3', image: 'led3.png', price: 900 },
  { category: 'profile', name: 'לד דגם 4', image: 'led4.png', price: 900 },
  { category: 'profile', name: 'לד דגם 5', image: 'led5.png', price: 1000 },
  { category: 'profile', name: 'לד דגם 6', image: 'led6.png', price: 1000 },
  { category: 'profile', name: 'לד דגם 7', image: 'led7.png', price: 1000 },
  { category: 'profile', name: 'לד דגם 8', image: 'led8.png', price: 1100 },
  { category: 'profile', name: 'לד דגם 9', image: 'led9.png', price: 1100 },
  { category: 'profile', name: 'לד דגם 10', image: 'led10.png', price: 1200 },
  { category: 'profile', name: 'לד דגם 11', image: 'led11.png', price: 1300 },
  { category: 'profile', name: 'לד דגם 12', image: 'led12.png', price: 1400 },
  { category: 'profile', name: 'לד דגם 13', image: 'led13.png', price: 1400 },
  { category: 'profile', name: 'לד דגם 14', image: 'led14.png', price: 1500 },
  { category: 'profile', name: 'לד דגם 15', image: 'led15.png', price: 1500 },
  { category: 'profile', name: 'לד דגם 16', image: 'led16.png', price: 1900 },
];